"""orders customer_id update

Revision ID: 3acfc1578b0c
Revises: 949a2219b223
Create Date: 2026-07-01 17:13:21.839517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3acfc1578b0c'
down_revision: Union[str, None] = '949a2219b223'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
