"""add trnx_id field on the payments table

Revision ID: 3ea341dd29bb
Revises: 786664c40b2c
Create Date: 2026-07-03 04:47:30.211409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ea341dd29bb'
down_revision: Union[str, None] = '786664c40b2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_id', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_payments_transaction_id', ['transaction_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_constraint('uq_payments_transaction_id', type_='unique')
        batch_op.drop_column('transaction_id')

    # ### end Alembic commands ###
