"""add customer name field on the orders table

Revision ID: 65c1f1b526c0
Revises: 3acfc1578b0c
Create Date: 2026-07-03 00:42:38.023893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65c1f1b526c0'
down_revision: Union[str, None] = '3acfc1578b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(), nullable=True))
        batch_op.drop_index('ix_orders_customer_id')
        batch_op.create_index(batch_op.f('ix_orders_customer_name'), ['customer_name'], unique=False)
        batch_op.drop_column('customer_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_id', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_orders_customer_name'))
        batch_op.create_index('ix_orders_customer_id', ['customer_id'], unique=False)
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
