"""orders and businesses relationship

Revision ID: 949a2219b223
Revises: f2ce00cd3b01
Create Date: 2026-07-01 15:50:24.553463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949a2219b223'
down_revision: Union[str, None] = 'f2ce00cd3b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
