"""db refactor

Revision ID: 99566938573d
Revises: e3a807107261
Create Date: 2026-07-09 17:50:42.277536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99566938573d'
down_revision: Union[str, None] = 'e3a807107261'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    naming_convention = {
        "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    }

    with op.batch_alter_table(
        'order_items', schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        batch_op.drop_constraint('fk_order_items_product_id_products', type_='foreignkey')

    with op.batch_alter_table(
        'orders', schema=None, naming_convention=naming_convention
    ) as batch_op:
        batch_op.add_column(sa.Column('customer_whatsapp_id', sa.String(), nullable=True))
        batch_op.drop_index('ix_orders_customer_name')
        batch_op.create_index(batch_op.f('ix_orders_customer_whatsapp_id'), ['customer_whatsapp_id'], unique=False)
        batch_op.drop_constraint('fk_orders_business_id_businesses', type_='foreignkey')
        batch_op.drop_column('customer_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(None, 'businesses', ['business_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_orders_customer_whatsapp_id'))
        batch_op.create_index('ix_orders_customer_name', ['customer_name'], unique=False)
        batch_op.drop_column('customer_whatsapp_id')

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.alter_column('product_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
